version: 2
jobs:
  build:
    working_directory: ~/android-demo-app
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup Emulator
          command: sdkmanager "system-images;android-28;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-28;default;armeabi-v7a"

      - run:
          name: Run Emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait for emulator to start
          command: circle-android wait-for-boot
      - run:
          name: Disable animations on an emulator
          command: |
            adb shell settings put global window_animation_scale 0 &
            adb shell settings put global transition_animation_scale 0 &
            adb shell settings put global animator_duration_scale 0
      - run:
          name: Run UI tests
          command: ./gradlew app:connectedAndroidTest
      - store_artifacts:
          path: app/build/reports/ui
          destination:  reports
      - store_test_results:
          path: app/build/ui
